module.exports = {
    city: [{
        value: null,
        label: '全部城市'
    }, {
        value: '大连',
        label: '大连'
    }, {
        value: '北京',
        label: '北京'
    }, {
        value: '天津',
        label: '天津'
    }, {
        value: '上海',
        label: '上海'
    }, {
        value: '南京',
        label: '南京'
    }, {
        value: '苏州',
        label: '苏州'
    }, {
        value: '南通',
        label: '南通'
    }, {
        value: '杭州',
        label: '杭州'
    }, {
        value: '合肥',
        label: '合肥'
    }, {
        value: '福州',
        label: '福州'
    }, {
        value: '厦门',
        label: '厦门'
    }, {
        value: '漳州',
        label: '漳州'
    }, {
        value: '济南',
        label: '济南'
    }, {
        value: '青岛',
        label: '青岛'
    }, {
        value: '烟台',
        label: '烟台'
    }, {
        value: '郑州',
        label: '郑州'
    }, {
        value: '洛阳',
        label: '洛阳'
    }, {
        value: '武汉',
        label: '武汉'
    }, {
        value: '长沙',
        label: '长沙'
    }, {
        value: '广州',
        label: '广州'
    }, {
        value: '深圳',
        label: '深圳'
    }, {
        value: '珠海',
        label: '珠海'
    }, {
        value: '重庆',
        label: '重庆'
    }, {
        value: '成都',
        label: '成都'
    }, {
        value: '贵阳',
        label: '贵阳'
    }, {
        value: '西安',
        label: '西安'
    }, {
        value: '台北',
        label: '台北'
    }, {
        value: '香港',
        label: '香港'
    }, {
        value: '海外',
        label: '海外'
    }, {
        value: '其他',
        label: '其它'
    }]
}